Mj/use xrpljs
ripple/xrp-batch-payout pull request #147
Opened 2021-11-17 22:39 UTC by mukulljangid

## High Level Overview of Change
Replace `gRPC` with `WebSocket`.

### Context of Change
`gRPC` is deprecated. This task is accomplished by using `xrpl.js` instead of the old `xpring-js`.

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Chore (project configuration, scripts, dotfiles, etc.)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

## Before / After
Functionalities work as expected.

## Test Plan
Passes CI tests. (Tests for the functions that were implemented in this library are deleted.)

2021-11-17 22:46 UTC, sappenin approved these changes
LGTM!

2021-11-17 22:51 UTC, theotherian requested changes
A few minor things to address but looks good otherwise. I'd like @florent-uzio to have a look too before merging.

2021-11-17 22:51 UTC, theotherian commented on README.md
> +  serverUrl - The web gRPC endpoint for the rippleD node.
Comment is wrong; it's no longer a gRPC node.

2021-11-17 22:51 UTC, theotherian commented on src/apps/payout.ts
> +      black(`  -> RippleD node web gRPC endpoint: ${senderInput.serverUrl}`),
This info needs to be updated too.

2021-11-17 22:51 UTC, theotherian commented on src/apps/payout.ts
> +    await client.connect()
Maybe a try/catch here in case it fails so we can write out a log message?

2021-11-17 22:51 UTC, theotherian commented on src/lib/config.ts
>  import { XrplNetwork } from 'xpring-js'
We should be able to remove these imports now as well as the dependency.

2021-11-17 22:56 UTC, mukulljangid commented on README.md
> +  serverUrl - The web gRPC endpoint for the rippleD node.
I agree

2021-11-17 23:38 UTC, mukulljangid commented on src/apps/payout.ts
> +    await client.connect()
This entire function is in a try-catch already and errors seem to be getting caught.

2021-11-18 10:36 UTC, florent-uzio requested changes
Good job! I left a few comments, some things to change in my opinion.

2021-11-18 10:36 UTC, florent-uzio commented on README.md
> +  "serverUrl": "https://s1.ripple.com",
The WebSocket should be `wss://s1.ripple.com`.

2021-11-18 16:35 UTC, florent-uzio approved these changes
LGTM

2021-11-18 20:53 UTC, theotherian approved these changes

2021-11-18 20:54 UTC, theotherian commented on src/apps/payout.ts
> +    await client.connect()
My mistake there; sorry!

2021-11-18 21:19 UTC, merged