bump version to 2.0.0
ripple/xrp-batch-payout pull request #148
Opened 2021-11-18 23:05 UTC by mukulljangid

## High Level Overview of Change
Bump up version to 2.0.0

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Chore (project configuration, scripts, dotfiles, etc.)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [X] Release

2021-11-18 23:42 UTC, sappenin requested changes

2021-11-18 23:42 UTC, sappenin commented on package.json
> +  "author": "Mukul Jangid",
Let's maybe remove `author` (assuming npm will still work?)

2021-11-19 16:18 UTC, sappenin approved these changes

2021-11-19 16:19 UTC, sappenin commented
@mukulljangid Looks like the build is failing...can you investigate?

2021-11-19 20:25 UTC, mukulljangid commented
> @mukulljangid Looks like the build is failing...can you investigate?

Has been resolved now!

2021-11-19 20:52 UTC, theotherian approved these changes

2021-11-19 20:56 UTC, sappenin approved these changes

2021-11-22 17:00 UTC, theotherian approved these changes

2021-11-23 16:14 UTC, merged