chore: Remove unused deps
ripple/xrp-batch-payout pull request #164
Opened 2021-12-07 15:26 UTC by mukulljangid

## High Level Overview of Change
Remove unused dependencies and cleanup the repository.

### Type of Change

- [X] Chore (project configuration, scripts, dotfiles, etc.)

## Test Plan
Passes CI tests

2021-12-08 22:12 UTC, theotherian commented on .eslintrc.js
> -  ],
Isn't this turning off a lot of linting rules in the process?

2021-12-08 22:14 UTC, theotherian requested changes
Mostly seems fine but I'm confused by removing the base eslint rules; seems like that turns off a lot of stuff. Just want a comment on that and will go from there.

2021-12-14 20:17 UTC, theotherian approved these changes

2021-12-14 22:27 UTC, sappenin approved these changes

2021-12-15 17:15 UTC, merged